services:
  - type: web
    name: zoom-discord-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: REDIS_URL
        fromService:
          name: redis
          type: redis
          property: connectionString

  - type: redis
    name: redis
    ipAllowList: []
    plan: free

  - type: worker
    name: celery-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A app.tasks worker --loglevel=info
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: REDIS_URL
        fromService:
          name: redis
          type: redis
          property: connectionString 